version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  unit-test-latest-go:
    docker:
      - image: golang:stretch
    steps:
      - checkout
      - run:
          name: Build project and perform tests
          command: make test
  unit-test-go:
      docker:
        - image: circleci/golang:1.16
      steps:
        - checkout
        - run:
            name: Build project and perform tests
            command: make test
        - codecov/upload:
            file: ./single.coverprofile
  benchmarks:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run:
          name: Build project and perform tests
          command: make benchmark

workflows:
  version: 2
  test:
    jobs:
      - unit-test-go
      - unit-test-latest-go
      - benchmarks
