[package]
name = "krach"
version = "0.1.0"
authors = ["Till Klocke <till.klocke@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_cbor = {version="0.9", default-features=true}
#ed25519-dalek = {version="0.9", features=["serde"]}
